general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Noto Sans Mono"
# family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Noto Sans Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Noto Sans Mono"
# family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
style = "Italic"

[font.normal]
family = "Noto Sans Mono"
# family = "MesloLGS Nerd Font Mono"
style = "Regular"
